apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  labels:
    state.aaw.statcan.gc.ca/non-employee-users: "true"
  name: alice-disallowed
  namespace: alice
spec:
  template:
    spec:
      containers:
      - env:
        - name: KF_LANG
          value: en
        image: k8scc01covidacr.azurecr.io/sas:0123
        name: alice-disallowed
        resources:
          limits:
            cpu: "100m"
            memory: 30Mi
          requests:
            cpu: "100m"
            memory: 30Mi
      serviceAccountName: default-editor
      volumes: []
