apiVersion: v1
kind: Pod
metadata:
  name: nginx-volume-types-disallowed
  labels:
    app: nginx-volume-types
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /cache
      name: cache
  - name: nginx2
    image: nginx
    volumeMounts:
    - mountPath: /cache2
      name: cache2
  volumes:
  - name: cache
    hostPath:
      path: /tmp
  - name: cache2
    emptyDir: {}
