apiVersion: constraints.gatekeeper.sh/v1beta1
kind: DenyExtraction
metadata:
  name: restrict-protected-b
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["PodExecOptions", "PodAttachOptions"]
  parameters:
    podLabels:
      - key: data.statcan.gc.ca/classification
        value: protected-b
