apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RestrictHostnames
metadata:
  name: restrict-hostnames
spec:
  match:
    kinds:
      - apiGroups: ["networking.k8s.io"]
        kinds: ["Ingress"]
      - apiGroups: ["networking.istio.io"]
        kinds: ["VirtualService"]
  parameters:
    exemptions:
      - '*.example.ca'
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    ingress.statcan.gc.ca/allowed-hosts: '[{"host": "test.com","path":"/FINance"}]'
  name: restrict-hostnames
