apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-account-bad
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-service-account
  labels:
    app: nginx-service-account
spec:
  serviceAccountName: test-account-bad
  automountServiceAccountToken: true
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: "100m"
        memory: "30Mi"
