apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: denypipelines
spec:
  crd:
    spec:
      names:
        kind: DenyPipelines
      validation:
        openAPIV3Schema:
          properties: {}
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package denypipelines

        violation[{"msg": msg}] {
          pod := input.review.object

          # If it's owned by a Workflow
          pod.metadata.ownerReferences[_].kind == "Workflow"

          msg := sprintf("Pod associated with forbidden pipeline run <%v/%v>", [input.review.namespace, input.review.name])
        }
