# https://raw.githubusercontent.com/Azure/azure-policy/master/built-in-references/Kubernetes/load-balancer-no-public-ips/constraint.yaml
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: LoadBalancerNoPublicIPs
metadata:
  name: loadbalancer-no-public-ips
spec:
  match:
    excludedNamespaces: ["istio-system"]
    kinds:
      - apiGroups: [""]
        kinds: ["Service"]
